### ISSUE TITLE
archived_orders

### ISSUE THREAD

**Issue by npomfret** [ShaunR/php-cexio#1]
I'm unable to get the dateTo and dateFrom parameters working in a call to archived_orders.  Any ideas?

**Comment by ShaunR** [comment]
Can you show me the exact method and params your sending?

**Comment by npomfret** [comment]
Just to clarify, i'm not using your code.  Just saw your project an wondered if you have used the archived_orders command.  I can't get the date parameters to work, no matter what values I use I get several hundred trades in the response.  The following attempts to get trades for  single day (2017-06-19).

Executing POST request at https://cex.io/api/archived_orders/BTC/GBP 


Request body = `key=mykey&signature=mysig&nonce=470602106&dateFrom=1497830400&dateTo=1497916800&status=d 
`

**Comment by ShaunR** [comment]
Have you tried contacting them to see if they can give you any help? I'd recommend you go that route.
